server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/my_library?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=true
    username: root
    password: autocrypt
    hikari:
      maximum-pool-size: 2
      connection-timeout: 300000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
springdoc:
  packages-to-scan: com.jinu.mylibrary
  swagger-ui:
    enabled: true